#!/usr/bin/env python3
"""
Trace Optimize Skill (root-level entry script)
This script reads:
- work_skill_path: path to the skill to optimize
- trace_data_path: path to trace data generated by the skill
- analysis_results_path: path to analysis results from trace analyzer
- output_dir: destination for improved skill and reports

It performs:
- Traditional anomaly detection on extracted features from traces
- Optional LL model augmentation for deeper insights
- Generates an improved skill package and a detailed report
"""
import argparse
import json
import os
import shutil
from pathlib import Path
from typing import List, Dict

import numpy as np
yaml_mod = None

from scripts.anomaly_detection import detect_anomalies
from llm_engine import LLMClient
import importlib
try:
    from pathlib import Path as _Path
    import yaml as yaml_mod
    YAML_AVAILABLE = True
except Exception:
    yaml_mod = None
    YAML_AVAILABLE = False


def load_json(path: Path) -> dict:
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return {}


def collect_traces(trace_dir: Path) -> List[Dict]:
    traces: List[Dict] = []
    if not trace_dir.exists():
        return traces
    for p in trace_dir.glob("**/*"):
        if p.is_file() and p.suffix in (".json", ".trace", ".log"):
            data = load_json(p) if p.suffix == ".json" else {}
            trace_id = p.stem
            traces.append({"trace_id": trace_id, "path": str(p), "data": data})
    return traces


def load_analysis_results(results_dir: Path) -> List[dict]:
    results: List[dict] = []
    if not results_dir.exists():
        return results
    for p in sorted(results_dir.glob("**/*.json")):
        j = load_json(p)
        if j:
            results.append({"path": str(p), "content": j})
    return results


def extract_features(traces: List[Dict]) -> List[Dict]:
    features = []
    for t in traces:
        data = t.get("data", {}) or {}
        latency = data.get("latency_ms") or data.get("duration_ms") or data.get("time_ms") or 0
        errors = int(data.get("errors", 0))
        feature = {
            "trace_id": t.get("trace_id"),
            "latency_ms": float(latency),
            "errors": errors,
        }
        features.append(feature)
    return features


def _load_llm_config_yaml() -> dict:
    # Look for llm_config.yaml in the trace-optimize-skill root (sibling to scripts/)
    try:
        base_dir = Path(__file__).resolve().parent.parent  # trace-optimize-skill
        config_path = base_dir / "llm_config.yaml"
        if config_path.exists() and YAML_AVAILABLE and yaml_mod is not None:
            with open(config_path, 'r', encoding='utf-8') as f:
                return yaml_mod.safe_load(f) or {}
    except Exception:
        pass
    return {}


def llm_assist(anomalies: List[Dict], context: str) -> str:
    # Try to load YAML config first
    config = {}
    if YAML_AVAILABLE:
        config = _load_llm_config_yaml() or {}
    # If config loaded and enabled, use LLM; otherwise fall back to heuristic
    use_llm = (config.get("enabled", True) and
               config.get("provider") in ("openrouter", "glm", "trace-llm"))
    if not anomalies:
        return "No anomalies detected; traditional trace optimization suggestions suffice."
    if not use_llm:
        count = len(anomalies)
        suggest = (
            f"Identified {count} anomalous traces. Prioritize: 1) stabilize latency via backend throttling and caching; "
            f"2) improve error handling and retry policies; 3) enhance trace granularity for better diagnostics."
        )
        return suggest
    # Use LLM via LLMClient
    try:
        llm_client = LLMClient(config or {})
        return llm_client.generate_insights(anomalies, context)
    except Exception:
        return "LLM integration error; fallback to heuristic suggestions."


def synthesize_recommendations(anomalies: List[Dict], llm_insights: str) -> List[Dict[str, str]]:
    recs: List[Dict[str, str]] = []
    recs.append({"type": "architecture", "text": "Add centralized trace collection with consistent schema across work skill instances."})
    recs.append({"type": "config", "text": "Enhance trace verbosity selectively via configurable levels; preserve production performance."})
    recs.append({"type": "runtime", "text": "Introduce automatic anomaly-triggered alerts and auto-tuning parameters."})
    recs.append({"type": "data", "text": "Ensure trace data includes timestamps, correlation IDs, and unique trace IDs for end-to-end tracing."})
    if anomalies:
        recs.append({"type": "targeted", "text": f"Investigate {len(anomalies)} anomalous traces to identify root causes (logs, external services, DB latency)."})
    if llm_insights:
        recs.append({"type": "llm", "text": f"LLM insights: {llm_insights}"})
    return recs


def copy_and_patch_skill(original_skill_path: Path, output_dir: Path, recommendations: List[Dict[str, str]]) -> Path:
    dest = output_dir / "improved_skill"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(original_skill_path, dest)
    patch_notes = dest / "trace_improvements.md"
    with open(patch_notes, 'w', encoding='utf-8') as f:
        f.write("# Trace Improvements\n\n")
        f.write("This improved skill includes enhancements guided by trace analysis and LL model insights.\n\n")
        f.write("## Recommendations\n")
        for i, r in enumerate(recommendations, 1):
            f.write(f"{i}. [{r['type']}] {r['text']}\n")
    return dest


def write_report(report_path: Path, anomalies: List[Dict], llm_insights: str, recommendations: List[Dict[str, str]]):
    md = []
    md.append("# Trace Optimization Report\n")
    md.append("## Summary\n")
    md.append(f"Anomalies detected: {len(anomalies)}.\n")
    if llm_insights:
        md.append("## LLM Insights\n")
        md.append(f"{llm_insights}\n")
    md.append("## Recommendations\n")
    for idx, r in enumerate(recommendations, 1):
        md.append(f"{idx}. [{r['type']}] {r['text']}\n")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, 'w', encoding='utf-8') as f:
        f.writelines([line for line in md])


def write_summary_json(summary_path: Path, data: dict):
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with open(summary_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--work-skill-path", required=True, help="Path to the working skill (source) directory")
    parser.add_argument("--trace-data-path", required=True, help="Path to trace data produced by the working skill")
    parser.add_argument("--analysis-results-path", required=True, help="Path to trace analysis results (from trace-analyzer)")
    parser.add_argument("--output-dir", required=True, help="Directory to write outputs (improved skill, reports, summaries)")
    args = parser.parse_args()

    work_skill_path = Path(args.work_skill_path).resolve()
    trace_data_path = Path(args.trace_data_path).resolve()
    analysis_results_path = Path(args.analysis_results_path).resolve()
    output_dir = Path(args.output_dir).resolve()

    traces = collect_traces(trace_data_path)
    results = load_analysis_results(analysis_results_path)
    features = extract_features(traces)
    anomalies = detect_anomalies(features)

    context = {
        "trace_count": len(traces),
        "anomaly_count": len(anomalies),
        "results_count": len(results),
    }
    context_text = json.dumps(context, indent=2)

    llm_insights = llm_assist(anomalies, context_text)
    recommendations = synthesize_recommendations(anomalies, llm_insights)

    improved_skill_path = copy_and_patch_skill(work_skill_path, output_dir, recommendations)

    report_path = output_dir / "improvement_report.md"
    write_report(report_path, anomalies, llm_insights, recommendations)
    summary_path = output_dir / "summary.json"
    summary = {
        "summary_generated_at": __import__("datetime").datetime.now().isoformat(),
        "input": {
            "work_skill_path": str(work_skill_path),
            "trace_data_path": str(trace_data_path),
            "analysis_results_path": str(analysis_results_path),
        },
        "analysis": {
            "trace_count": len(traces),
            "anomalies": anomalies,
            "analysis_results_count": len(results),
        },
        "recommendations": recommendations,
        "llm_insights": llm_insights,
    }
    write_summary_json(summary_path, summary)

    print(f"Trace optimization completed. Improved skill written to: {improved_skill_path}")
    print(f"Report: {report_path}")
    print(f"Summary: {summary_path}")


if __name__ == "__main__":
    main()
